# Numpy Basic

In [65]:
import numpy as np

## data type

array의 dtype을 본다. 

In [71]:
arr = np.array([[1., 2, 3], [1, 2, 3]])

In [72]:
arr.dtype

dtype('float64')

.astype()으로 datatype을 변환 가능

In [76]:
arr = arr.astype(np.uint8)
arr

array([[1, 2, 3],
       [1, 2, 3]], dtype=uint8)

In [75]:
arr.dtype

dtype('uint8')

len(arr.shape) 를 통해서 차원의 갯수를 확인 할 수 있지만,  
아래와 같이 ndim을 통해 차원 수를 return 가능

In [77]:
len(arr.shape)

2

In [78]:
arr.shape

(2, 3)

size 확인

In [79]:
arr.size

6

dtype 확인

In [80]:
arr.dtype

dtype('uint8')

## Reshape

In [81]:
arr.shape

(2, 3)

Reshape 

In [86]:
arr = arr.reshape([1, 6])
arr.shape

(1, 6)

In [87]:
arr = np.array([[1, 2, 3], [1, 2, 3]])

In [88]:
arr.reshape([6]).shape

(6,)

Reshape, -1 활용

In [89]:
arr = arr.reshape(-1)
arr.shape

(6,)

In [92]:
arr = arr.reshape(-1, 3)
arr.shape

(2, 3)

random array 생성

In [93]:
arr = np.random.randn(8, 8)
arr.shape

(8, 8)

In [94]:
arr = arr.reshape([32, 2])
arr.shape

(32, 2)

3차원으로 늘리기

In [95]:
arr = arr.reshape(-1, 2, 1, 1, 1)
arr.shape

(32, 2, 1, 1, 1)

## Ravel

In [97]:
arr.shape

(32, 2, 1, 1, 1)

In [99]:
arr = arr.ravel()
arr

array([ 0.72799127,  1.17100142, -1.22207935,  0.58910163, -1.41104497,
        0.6043916 , -0.93435445,  0.84569002, -0.4654336 ,  0.61918303,
        1.74709223,  1.42320429,  2.66563005,  1.37654502, -0.87188756,
        0.74854725,  0.44890722, -1.11602789, -0.44144245, -1.35728799,
        0.93628504,  0.64823296, -0.02283505, -0.20393321, -0.30198145,
        2.3001046 ,  0.45075883,  1.48577996, -0.33521106,  0.00546056,
       -0.11504615, -0.23132481, -1.42521782,  0.97423533, -0.15773336,
        1.65802148, -1.61258647, -1.93708993,  0.18494056, -0.21234519,
       -1.59843653, -0.08464429,  2.51529752,  0.8275372 , -0.98926774,
       -1.85501698,  1.52459239,  1.71853955,  2.36082965, -0.09009807,
       -0.38702011,  1.58338144,  0.34753317, -0.37740283, -0.6682165 ,
        0.78537683, -0.27628795,  0.14376355,  2.45834229, -0.59334636,
        0.55185745,  1.70887238,  0.99566109, -1.43367579])

arr의 차원을 1로 바꿔줌  
나중에 배울 layer를 flatten 할 때 같은 기능이라 생각하면 됨 

arr.reshape(-1) 와 같음

In [100]:
arr.ravel() == arr.reshape(-1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## np.expand_dims()

안의 값은 유지하되 차원 수를 늘리고 싶을 때가 있음  
이럴 때 사용하는 것이 expand_dims  

In [101]:
arr.shape

(64,)

In [102]:
arr = np.expand_dims(arr, 0)
arr.shape

(1, 64)

In [104]:
arr = arr.ravel()

In [105]:
arr.shape

(64,)

In [106]:
arr = np.expand_dims(arr, -1)
arr.shape

(64, 1)

## zeros & ones

0으로 채워진 numpy array를 만들 수 있음

In [7]:
zeros = np.zeros([3, 3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
zeros = np.zeros(1)
zeros

array([0.])

In [9]:
ones = np.ones([10, 5])
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
ones * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [12]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [13]:
arr = np.arange(4, 9)
arr

array([4, 5, 6, 7, 8])

In [15]:
arr = np.arange(10,20)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# Index

In [17]:
nums = [1, 2, 3, 4, 5]

In [19]:
nums[2:]

[3, 4, 5]

In [21]:
nums = [1, 2, 3, 4, [1, 2, 3]]
nums

[1, 2, 3, 4, [1, 2, 3]]

In [22]:
nums[4]

[1, 2, 3]

In [23]:
arr[1][2]

5

In [24]:
arr[1, 2]

5

# Slicing

In [25]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
arr[1:]

array([[3, 4, 5],
       [6, 7, 8]])

In [27]:
arr[1:, 1:]

array([[4, 5],
       [7, 8]])

## Boolean Indexing

In [29]:
data = np.random.randn(3, 3)
data

array([[ 0.32019405,  0.88306094,  1.56154565],
       [ 0.4929685 , -1.49015153, -0.90176214],
       [-0.73970725, -0.22397648,  2.83966483]])

In [30]:
data <= 0

array([[False, False, False],
       [False,  True,  True],
       [ True,  True, False]])

In [31]:
data[data <= 0] = 1
data

array([[0.32019405, 0.88306094, 1.56154565],
       [0.4929685 , 1.        , 1.        ],
       [1.        , 1.        , 2.83966483]])

# Broadcast

tensorflow나 pytorch로 계산하면 broadcast의 개념도 잘 이해해야 함

broadcast는 연산 하려는 서로 다른 두개의 행렬의 shape가 같지 않고,  
한쪽의 차원이라도 같거나 또는 값의 갯수가 한 개 일 때  
이를 여러 복사를 하여 연산을 함

In [33]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
arr + 3

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [37]:
arr + np.array([1, 2, 3])

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

## Math Function

In [38]:
arr + 10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [39]:
arr * 5

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [40]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [41]:
np.add(arr, 1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr + 1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
np.multiply(arr, 3)

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [45]:
arr = np.random.randint(2, size=27).reshape(3, 3, 3)
arr_2 = np.random.randint(2, size=9).reshape(3, 3)

In [46]:
arr

array([[[1, 0, 0],
        [1, 0, 1],
        [0, 1, 0]],

       [[1, 1, 0],
        [1, 0, 1],
        [0, 1, 1]],

       [[0, 0, 1],
        [0, 1, 0],
        [0, 1, 0]]])

In [47]:
arr.shape

(3, 3, 3)

In [49]:
arr_2.shape, arr.shape

((3, 3), (3, 3, 3))

In [50]:
arr * arr_2

array([[[0, 0, 0],
        [0, 0, 1],
        [0, 1, 0]],

       [[0, 0, 0],
        [0, 0, 1],
        [0, 1, 0]],

       [[0, 0, 1],
        [0, 0, 0],
        [0, 1, 0]]])

In [51]:
np.sum(arr)

13

In [52]:
np.sum(arr + arr_2)

22

In [53]:
np.max(arr + arr_2)

2

In [54]:
np.min(arr + arr_2)

0

In [55]:
np.max(arr + arr_2, 0)

array([[1, 1, 2],
       [1, 1, 2],
       [0, 2, 1]])

In [56]:
arr + arr_2

array([[[1, 0, 1],
        [1, 0, 2],
        [0, 2, 0]],

       [[1, 1, 1],
        [1, 0, 2],
        [0, 2, 1]],

       [[0, 0, 2],
        [0, 1, 1],
        [0, 2, 0]]])

In [57]:
np.sum(arr + arr_2, -1)

array([[2, 3, 2],
       [3, 3, 3],
       [2, 2, 2]])

In [58]:
np.mean(arr)

0.48148148148148145

In [59]:
arr = np.array([1, 6, 3, 7, 3, 2, 9])

In [60]:
np.argmax(arr)

6

In [61]:
np.argmin(arr)

0

In [62]:
arr = np.array([3, 5, 6, 6, 3, 3, 1])

In [63]:
np.unique(arr)

array([1, 3, 5, 6])